### ISSUE TITLE
Making a CL with \n results in error

### ISSUE THREAD

**Issue by nielsvaes** [nielsvaes/p4cmd#5]
```Python
cl = p4.get_or_make_changelist("Deleting non-used animations, matching CL308545.\n They hung in the sky in much the same way that bricks don't.")
print(cl)
```

C:\Python39\python.exe C:\Users\niels.vaes\AppData\Roaming\JetBrains\PyCharm2023.2\scratches\p4cmd_tester.py 
```
Traceback (most recent call last):
  File "C:\Users\niels.vaes\AppData\Roaming\JetBrains\PyCharm2023.2\scratches\p4cmd_tester.py", line 598, in <module>
    cl = p4.get_or_make_changelist("Deleting non-used animations, matching CL308545.\n They hung in the sky in much the same way that bricks don't.")
  File "D:\git\embark_dev\p4cmd\p4cmd\p4cmd.py", line 754, in get_or_make_changelist
    return self.make_new_changelist(description=changelist_description)
  File "D:\git\embark_dev\p4cmd\p4cmd\p4cmd.py", line 287, in make_new_changelist
    return int(changelist_number)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by nielsvaes** [comment]
Fixed in fa1c4ca on the `claude-updates` branch.\n\nThe root cause was that the description was interpolated directly into a shell command string, so any `\n` in the description broke the p4 command. The fix fetches the blank changelist template with `p4 change -o`, replaces the Description field in Python (preserving newlines with proper tab-indentation), and feeds the result to `p4 change -i` via stdin — the same approach already used by `update_changelist_description`.
